### ISSUE TITLE
Wrong flag data for Venezuela

### ISSUE THREAD

**Issue by PineappleRind** [shanuraj715/all-country-data#1] opened 2022-06-13 02:07 UTC
The base64 flag data for Vanuatu and Venezuela are both the same (vanuatu's flag)

**Comment by shanuraj715** [comment] 2022-08-06 06:43
The issue is resolved with patch version 0.2.3. It is published on npmjs.org. Thank you for your support. <3

**Closed as completed by shanuraj715** 2022-08-06 06:43 UTC
